name: Deployment (Development)

on:
  push:
    branches-ignore:
      - 'main'
      - 'release/**'
      - 'legacy-**'

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: [test]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      stage: dev
    secrets: inherit